#
###################################
# Site wide configuration
####################################
#
title: un0rick
email: kelu124@gmail.com
description: An open-source fpga-based ultrasound development kit.
url: http://un0rick.cc # the base hostname & protocol for your site
keywords: ["ultrasound", "fpga", "open source", "opensource", "hardware"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Europe/Paris
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: kelu
  avatar: leonids-logo.png
  job: "Tinkerer"
  bio: "Having fun tinkering with hardware, France."
  email: kelu@un0rick.cc
  disqus-shortname: kelu124
  twitter: kelu124 #username
  facebook: #username
  google:
    plus: #username
    analytics: UA-115122033-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: kelu124 #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  telegram: #username
